# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HidrowebDownloader
                                 A QGIS plugin
 Download hydrological data from ANA's API (Hidroweb)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-27
        copyright            : (C) 2021 by Alex Naoki Asato Kobayashi
        email                : alexkobayashi10@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HidrowebDownloader class from file HidrowebDownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hidroweb_downloader import HidrowebDownloader
    return HidrowebDownloader(iface)
